keys:
  # users (for scripts and such)
  - &desant age1elsaau30q4n00le29667vaepsc7zw8vlgdtx8twsq5623f35xuksznanpn

  # machines (for fywion services)
  - &legion age1xq2w69xtsmneukre6vlrd9q6ctms5psv3u03453cd73r3jpayqxsactz2k
  - &cynnil age1g35gwk8afy3gcr0pmm5kjr7v5rjh7nskcfuylvltkzgstwgqxp7sqm8p6f

creation_rules:
  # personal secrets
  - path_regex: secrets/desant\.yaml
    key_groups:
      - age:
          - *desant

  # service secrets
  - path_regex: secrets/services/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *desant
          - *legion
          - *cynnil
