{
  lib,
  self,
  _class,
  config,
  ...
}:
let
  inherit (lib.options) mkOption;
  inherit (lib.types) str;

  cfg = config.ceirios.system;
in
{
  options.ceirios.system.stateVersion = mkOption {
    type = str;
    default = "26.05";
    description = ''
      Whatever version of nixos was initially installed.
      This is important.
      Usually gets generated by nixos-generate-config on initial install and should be set here.
    '';
  };

  config.system = {
    # used by nixos for keeping breaking nixos changes at bay
    # should be whatever version was first installed
    stateVersion = if (_class == "nixos") then cfg.stateVersion else 6;

    # we can get the git rev that we are working on and set that to the configurationRevision
    # this *might* be useful for debugging
    configurationRevision = self.shortRev or self.dirtyShortRev or "dirty";
  };
}
