{
  pkgs,
  config,
  osConfig,
  lib,
  ...
}:

let
  inherit (lib.modules) mkIf;
  inherit (config.ceirios.profiles) graphical;
in
{
  imports = [ ./hyprsunset.nix ];

  config = mkIf graphical.enable {
    # whoever tf thought it's a good idea to make me rewrite
    # my hyprland config for the second time this year
    # (and it's only may) should reconsider their life choices

    wayland.windowManager.hyprland = {
      enable = true;

      # ew
      configType = "lua";

      # handled by nixos
      package = null;
      portalPackage = null;

      # we ball. merge raw lua into one file since that's gonna happen anyways
      extraConfig = ''
        -- import colors from matugen
        require("./colors")

        -------------------
        -- dynamic stuff --
        -------------------

        -- software vars --

        ${import ./vars.nix { inherit config osConfig lib; }}

        -- autogenerated monitors --

        ${import ./monitors.nix { inherit osConfig lib; }}

        -- autogenerated workspaces --

        ${import ./workspaces.nix { inherit lib osConfig; }}

        -- aquamarine --

        ${import ./aquamarine.nix { inherit osConfig lib; }}

        --------------
        -- the rest --
        --------------

        ${builtins.readFile ./input.lua}
        ${builtins.readFile ./keybinds.lua}
        ${builtins.readFile ./look_and_feel.lua}
        ${builtins.readFile ./windows.lua}
        ${builtins.readFile ./animations.lua}
      '';
    };

    # xdg-desktop-portal-hyprland config
    # https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland/
    xdg.configFile."hypr/xdph.conf".text = ''
      screencopy {
        max_fps = 60
        allow_token_by_default = true
      }
    '';
  };
}
