{
  pkgs,
  config,
  osConfig,
  lib,
  ...
}:

{
  config = lib.mkIf config.ceirios.profiles.graphical {
    ceirios.packages = { inherit (pkgs) hyprshot hyprsunset; };

    # whoever tf thought it's a good idea to make me rewrite
    # my hyprland config for the second time this year
    # (and it's only may) should reconsider their life choices

    wayland.windowManager.hyprland = {
      enable = true;

      # ew
      configType = "lua";

      # handled by nixos
      package = null;
      portalPackage = null;

      # TODO: the autostart section sucks

      # we ball. merge raw lua into one file since that's gonna happen anyways
      extraConfig = ''
        -- import colors from matugen
        require("./colors")

        -------------------
        -- dynamic stuff --
        -------------------

        -- software vars --

        ${import ./vars.nix { inherit config lib; }}

        -- autogenerated monitors --

        ${import ./monitors.nix { inherit osConfig lib; }}

        -- autogenerated workspaces --

        ${import ./workspaces.nix { inherit lib osConfig; }}

        -------------------------------------
        -- too small to have it's own file --
        -------------------------------------

        -- cursor env
        hl.env("XCURSOR_SIZE", "24")
        hl.env("XCURSOR_THEME", "Volantes Cursors")

        -- autostart
        hl.on("hyprland.start", function ()
          hl.exec_cmd(bar)
          hl.exec_cmd(wallpaper)
          hl.exec_cmd(polkit)
          hl.exec_cmd(filter)
        end)

        --------------
        -- the rest --
        --------------

        ${builtins.readFile ./input.lua}
        ${builtins.readFile ./keybinds.lua}
        ${builtins.readFile ./look_and_feel.lua}
        ${builtins.readFile ./windows.lua}
      '';
    };

    # FIXME: do we need this???
    # xdg-desktop-portal-hyprland config
    # https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland/
    # xdg.configFile."hypr/xdph.conf".text = ''
    #   screencopy {
    #     max_fps = 60
    #     allow_token_by_default = true
    #   }
    # '';
  };
}
