name: _Run nix flake update

on:
  workflow_call:
    inputs:
      inputs: # updates all if empty
        type: string
        default: ""
      commit_msg:
        type: string
        default: "flake: bump... something? (auto)"
    secrets:
      GH_TOKEN_UPDATES:
        required: true

permissions: {}

jobs:
  flake-update:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update all inputs
        if: inputs.inputs == ''
        id: pr_full
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_UPDATES }}
          git-author-name: Caterpillar
          git-author-email: pill@anturated.dev
          git-committer-name: Caterpillar
          git-committer-email: pill@anturated.dev
          commit-msg: ${{ inputs.commit_msg }}
          pr-title: ${{ inputs.commit_msg }}
          branch: pill-flake-update
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

      - name: Partial inputs update
        if: inputs.inputs != ''
        id: pr_specific
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_UPDATES }}
          git-author-name: Caterpillar
          git-author-email: pill@anturated.dev
          git-committer-name: Caterpillar
          git-committer-email: pill@anturated.dev
          commit-msg: ${{ inputs.commit_msg }}
          pr-title: ${{ inputs.commit_msg }}
          branch: pill-flake-update
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

      - name: Wait for Checks & Merge
        if: >
          steps.pr_full.outputs.pull-request-url != '' ||
          steps.pr_specific.outputs.pull-request-url != ''
        run: |
          # if we don't wait it fails
          sleep 30
          gh pr checks "$PR" --watch --fail-fast
          gh pr merge --rebase --delete-branch "$PR"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_UPDATES }}
          PR: >-
            ${{
              steps.pr_full.outputs.pull-request-url != '' &&
              steps.pr_full.outputs.pull-request-url ||
              steps.pr_specific.outputs.pull-request-url
            }}
