name: Run nix flake update

on:
  workflow_dispatch:
  schedule:
    - cron: "7 0 * * *"

permissions: {}

jobs:
  flake-update:
    name: Update flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run flake update
        id: pr
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_UPDATES }}
          git-author-name: Caterpillar
          git-author-email: pill@anturated.dev
          git-committer-name: Caterpillar
          git-committer-email: pill@anturated.dev
          commit-msg: "flake: bump (auto)"
          pr-title: "flake: bump (auto)"
          branch: pill-flake-update
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

      - name: Wait for Checks & Merge
        run: |
          # if we don't wait it fails
          sleep 30
          gh pr checks "$PR" --watch --fail-fast
          gh pr merge --rebase --delete-branch "$PR"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_UPDATES }}
          PR: ${{ steps.pr.outputs.pull-request-url }}
